version: '3.8'

services:
  bcm-api:
    build:
      context: ./BCM.Api
      dockerfile: Dockerfile
    container_name: bcm-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  bcm-web:
    build:
      context: ./BCM.Web
      dockerfile: Dockerfile
    container_name: bcm-web
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production